site: Chouyo LLC | 顧客とつなぐ、チームを結ぶ。

url: https://www.chouyo.ink
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /posts/:slug
  books:
    output: true
    permalink: /books/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "books"
    values:
      layout: "book"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Github Pagesはjekyll-paginate version 1.1.0を使用している。
# 当該バージョンはpostsのみページネーションできる。
# v2以降はcollectionなどもページネーションできるが、Github Actionなどを使用して頑張る必要がある。
# めんどくさいので一旦放置。
# TODO: jekyll-paginate-v2を使用できるようにする（https://talk.jekyllrb.com/t/paginate-v2-with-github-pages-confusion/6471）
paginate: 10
paginate_path: "/posts/page:num/"

grid_alignments:
  - top
  - center
  - bottom